/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AddAttributeForm: typeof import('./src/components/User/AddAttributeForm.vue')['default']
    AddMemberModal: typeof import('./src/components/Group/AddMemberModal.vue')['default']
    AddUserToGroupModal: typeof import('./src/components/Modals/AddUserToGroupModal.vue')['default']
    AdvancedConditionEditor: typeof import('./src/components/Policy/AdvancedConditionEditor.vue')['default']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AssignPermissionModal: typeof import('./src/components/Modals/AssignPermissionModal.vue')['default']
    ATag: typeof import('ant-design-vue/es')['Tag']
    AttributeHistory: typeof import('./src/components/User/AttributeHistory.vue')['default']
    BaseModal: typeof import('./src/components/Common/BaseModal.vue')['default']
    BooleanValueInput: typeof import('./src/components/Policy/ValueInputs/BooleanValueInput.vue')['default']
    ChangeAvatarModal: typeof import('./src/components/Modals/ChangeAvatarModal.vue')['default']
    ConditionEditor: typeof import('./src/components/Policy/ConditionEditor.vue')['default']
    ConditionTreeNode: typeof import('./src/components/Policy/ConditionTreeNode.vue')['default']
    ConfirmModal: typeof import('./src/components/Common/ConfirmModal.vue')['default']
    DateValueInput: typeof import('./src/components/Policy/ValueInputs/DateValueInput.vue')['default']
    DemoAccountsInfo: typeof import('./src/components/Common/DemoAccountsInfo.vue')['default']
    EditMemberModal: typeof import('./src/components/Group/EditMemberModal.vue')['default']
    EditUserModal: typeof import('./src/components/Modals/EditUserModal.vue')['default']
    GroupFormModal: typeof import('./src/components/Group/GroupFormModal.vue')['default']
    GroupList: typeof import('./src/components/Group/GroupList.vue')['default']
    GroupMembers: typeof import('./src/components/Group/GroupMembers.vue')['default']
    GroupModal: typeof import('./src/components/Group/GroupModal.vue')['default']
    GroupTree: typeof import('./src/components/Group/GroupTree.vue')['default']
    ImportModal: typeof import('./src/components/User/ImportModal.vue')['default']
    ListValueInput: typeof import('./src/components/Policy/ValueInputs/ListValueInput.vue')['default']
    LoadingSpinner: typeof import('./src/components/Common/LoadingSpinner.vue')['default']
    MainLayout: typeof import('./src/components/Layout/MainLayout.vue')['default']
    MemberManagementModal: typeof import('./src/components/Group/MemberManagementModal.vue')['default']
    MemberModal: typeof import('./src/components/Group/MemberModal.vue')['default']
    NumberValueInput: typeof import('./src/components/Policy/ValueInputs/NumberValueInput.vue')['default']
    PolicyEditorModal: typeof import('./src/components/Policy/PolicyEditorModal.vue')['default']
    PolicyTestModal: typeof import('./src/components/Policy/PolicyTestModal.vue')['default']
    RecordDetailModal: typeof import('./src/components/User/RecordDetailModal.vue')['default']
    ResetPasswordModal: typeof import('./src/components/Modals/ResetPasswordModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StringValueInput: typeof import('./src/components/Policy/ValueInputs/StringValueInput.vue')['default']
    TreeModal: typeof import('./src/components/Group/TreeModal.vue')['default']
    TreeNode: typeof import('./src/components/Group/TreeNode.vue')['default']
    UserAttributeModal: typeof import('./src/components/User/UserAttributeModal.vue')['default']
    UserInfo: typeof import('./src/components/Common/UserInfo.vue')['default']
    UserModal: typeof import('./src/components/User/UserModal.vue')['default']
  }
}
