/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    AddMemberModal: typeof import('./src/components/Group/AddMemberModal.vue')['default']
    AddUserToGroupModal: typeof import('./src/components/Modals/AddUserToGroupModal.vue')['default']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    AssignPermissionModal: typeof import('./src/components/Group/AssignPermissionModal.vue')['default']
    ATag: typeof import('ant-design-vue/es')['Tag']
    BaseModal: typeof import('./src/components/Common/BaseModal.vue')['default']
    ChangeAvatarModal: typeof import('./src/components/Modals/ChangeAvatarModal.vue')['default']
    ConfirmModal: typeof import('./src/components/Common/ConfirmModal.vue')['default']
    EditMemberModal: typeof import('./src/components/Group/EditMemberModal.vue')['default']
    EditUserModal: typeof import('./src/components/Modals/EditUserModal.vue')['default']
    GroupFormModal: typeof import('./src/components/Group/GroupFormModal.vue')['default']
    GroupList: typeof import('./src/components/Group/GroupList.vue')['default']
    GroupMembers: typeof import('./src/components/Group/GroupMembers.vue')['default']
    GroupModal: typeof import('./src/components/Group/GroupModal.vue')['default']
    GroupTree: typeof import('./src/components/Group/GroupTree.vue')['default']
    ImportModal: typeof import('./src/components/User/ImportModal.vue')['default']
    MainLayout: typeof import('./src/components/Layout/MainLayout.vue')['default']
    MemberManagementModal: typeof import('./src/components/Group/MemberManagementModal.vue')['default']
    MemberModal: typeof import('./src/components/Group/MemberModal.vue')['default']
    ResetPasswordModal: typeof import('./src/components/Modals/ResetPasswordModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreeModal: typeof import('./src/components/Group/TreeModal.vue')['default']
    TreeNode: typeof import('./src/components/Group/TreeNode.vue')['default']
    UserModal: typeof import('./src/components/User/UserModal.vue')['default']
  }
}
